version: '3.8'
services:
  omegal_clone:
    container_name: omegal_clone
    build: .
    depends_on:
      - redisserver
    ports:
      - 3030:3030
    links:
      - redisserver

volumes:
  socketsync:
    driver: local
